import { mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import {
  contentRows,
  enrichOpenApiDocument,
  isHttpMethod,
  operationKey,
  parameterRows,
  parametersByGroup,
  responseRows,
  validateOpenApiDocument,
  type FieldRow,
  type OpenApiDocument,
  type OperationObject
} from "./openapi-doc-quality.js"

process.env.MOCK_BEDROCK ??= "true"
process.env.USE_LOCAL_VECTOR_STORE ??= "true"
process.env.USE_LOCAL_QUESTION_STORE ??= "true"
process.env.USE_LOCAL_CONVERSATION_HISTORY_STORE ??= "true"
process.env.USE_LOCAL_BENCHMARK_RUN_STORE ??= "true"
process.env.USE_LOCAL_CHAT_RUN_STORE ??= "true"
process.env.USE_LOCAL_DOCUMENT_INGEST_RUN_STORE ??= "true"
process.env.LOCAL_DATA_DIR ??= ".local-data"

const outputDir = fileURLToPath(new URL("../../../docs/generated/", import.meta.url))
const openApiOutputPath = join(outputDir, "openapi.json")
const markdownOutputPath = join(outputDir, "openapi.md")

function escapeMarkdown(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ").trim()
}

function operationRows(api: OpenApiDocument): string[] {
  const rows = ["| Method | Path | Summary |", "| --- | --- | --- |"]
  for (const [path, pathItem] of Object.entries(api.paths ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!isHttpMethod(method)) continue
      rows.push(`| \`${method.toUpperCase()}\` | \`${path}\` | ${escapeMarkdown(operation.summary ?? "-")} |`)
    }
  }
  return rows
}

function fieldTable(rows: FieldRow[], emptyText = "_なし_"): string[] {
  if (rows.length === 0) return [emptyText]
  return [
    "| 項目 | 型 | 必須 | 説明 | 制約 |",
    "| --- | --- | --- | --- | --- |",
    ...rows.map((row) => `| \`${escapeMarkdown(row.name)}\` | \`${escapeMarkdown(row.type)}\` | ${row.required ? "yes" : "no"} | ${escapeMarkdown(row.description)} | ${row.constraints} |`)
  ]
}

function renderRequestData(api: OpenApiDocument, operation: OperationObject): string[] {
  const body = operation.requestBody
  if (!body || typeof body !== "object" || !("content" in body)) return ["_なし_"]
  const content = contentRows(api, body.content)
  if (content.length === 0) return ["_なし_"]
  const lines: string[] = []
  for (const item of content) {
    lines.push(`Media type: \`${item.mediaType}\``)
    lines.push("")
    lines.push(...fieldTable(item.rows))
    lines.push("")
  }
  return lines
}

function renderResponses(api: OpenApiDocument, operation: OperationObject): string[] {
  const responses = responseRows(api, operation.responses)
  if (responses.length === 0) return ["_なし_"]
  const lines: string[] = []
  for (const response of responses) {
    lines.push(`##### \`${response.status}\` ${response.description}`)
    lines.push("")
    lines.push(`Media type: \`${response.mediaType}\``)
    lines.push("")
    lines.push(...fieldTable(response.rows, response.mediaType === "-" ? "_body なし_" : "_項目なし_"))
    lines.push("")
  }
  return lines
}

function renderOperations(api: OpenApiDocument): string[] {
  const lines: string[] = []
  for (const [path, pathItem] of Object.entries(api.paths ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!isHttpMethod(method)) continue
      lines.push(`### ${operationKey(method, path)}`)
      lines.push("")
      lines.push(`Summary: ${operation.summary ?? "-"}`)
      lines.push("")
      lines.push(operation.description ?? "-")
      lines.push("")
      lines.push("#### Headers")
      lines.push("")
      lines.push(...fieldTable(parameterRows(parametersByGroup(operation, "header"))))
      lines.push("")
      lines.push("#### Path Parameters")
      lines.push("")
      lines.push(...fieldTable(parameterRows(parametersByGroup(operation, "path"))))
      lines.push("")
      lines.push("#### Query Parameters")
      lines.push("")
      lines.push(...fieldTable(parameterRows(parametersByGroup(operation, "query"))))
      lines.push("")
      lines.push("#### Data")
      lines.push("")
      lines.push(...renderRequestData(api, operation))
      lines.push("")
      lines.push("#### Responses")
      lines.push("")
      lines.push(...renderResponses(api, operation))
    }
  }
  return lines
}

function renderMarkdown(api: OpenApiDocument): string {
  const title = api.info?.title ?? "OpenAPI Reference"
  const version = api.info?.version ?? "-"
  const description = api.info?.description ?? ""
  const lines = [
    `# ${title}`,
    "",
    "<!-- This file is generated by npm run docs:openapi. Do not edit manually. -->",
    "",
    `OpenAPI: \`${api.openapi ?? "-"}\``,
    `Version: \`${version}\``,
    "",
    description,
    "",
    "## Operations",
    "",
    ...operationRows(api),
    "",
    "## Operation Details",
    "",
    ...renderOperations(api)
  ]
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`
}

async function main(): Promise<void> {
  const { default: app } = await import("./app.js")
  const response = await app.request("/openapi.json")
  if (!response.ok) {
    throw new Error(`Failed to generate OpenAPI document: ${response.status}`)
  }

  const api = enrichOpenApiDocument((await response.json()) as OpenApiDocument)
  const errors = validateOpenApiDocument(api)
  if (errors.length > 0) {
    throw new Error(`OpenAPI document quality check failed:\n${errors.map((error) => `- ${error}`).join("\n")}`)
  }

  await mkdir(outputDir, { recursive: true })
  await writeFile(openApiOutputPath, `${JSON.stringify(api, null, 2)}\n`)
  await writeFile(markdownOutputPath, renderMarkdown(api))

  console.log(`Generated ${openApiOutputPath}`)
  console.log(`Generated ${markdownOutputPath}`)
}

await main()
