import { mkdir, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import {
  contentRows,
  enrichOpenApiDocument,
  isHttpMethod,
  operationKey,
  parameterRows,
  parametersByGroup,
  responseRows,
  validateOpenApiDocument,
  type FieldRow,
  type OpenApiDocument,
  type OperationObject
} from "./openapi-doc-quality.js"

process.env.MOCK_BEDROCK ??= "true"
process.env.USE_LOCAL_VECTOR_STORE ??= "true"
process.env.USE_LOCAL_QUESTION_STORE ??= "true"
process.env.USE_LOCAL_CONVERSATION_HISTORY_STORE ??= "true"
process.env.USE_LOCAL_BENCHMARK_RUN_STORE ??= "true"
process.env.USE_LOCAL_CHAT_RUN_STORE ??= "true"
process.env.USE_LOCAL_DOCUMENT_INGEST_RUN_STORE ??= "true"
process.env.LOCAL_DATA_DIR ??= ".local-data"

const outputDir = fileURLToPath(new URL("../../../docs/generated/", import.meta.url))
const openApiOutputPath = join(outputDir, "openapi.json")
const markdownOutputPath = join(outputDir, "openapi.md")
const operationOutputDir = join(outputDir, "openapi")

function escapeMarkdown(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ").trim()
}

function operationRows(api: OpenApiDocument): string[] {
  const rows = ["| Method | Path | Summary | Detail |", "| --- | --- | --- | --- |"]
  for (const item of operationEntries(api)) {
    rows.push(`| \`${item.method.toUpperCase()}\` | \`${item.path}\` | ${escapeMarkdown(item.operation.summary ?? "-")} | [詳細](${item.filePath}) |`)
  }
  return rows
}

function operationEntries(api: OpenApiDocument): Array<{
  method: string
  path: string
  operation: OperationObject
  fileName: string
  filePath: string
}> {
  const entries: Array<{
    method: string
    path: string
    operation: OperationObject
    fileName: string
    filePath: string
  }> = []
  for (const [path, pathItem] of Object.entries(api.paths ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!isHttpMethod(method)) continue
      const fileName = `${operationSlug(method, path)}.md`
      entries.push({
        method,
        path,
        operation,
        fileName,
        filePath: `openapi/${fileName}`
      })
    }
  }
  return entries
}

function operationSlug(method: string, path: string): string {
  const pathSlug = path
    .replaceAll("{", "")
    .replaceAll("}", "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
  return `${method.toLowerCase()}-${pathSlug || "root"}`
}

function fieldTable(rows: FieldRow[], emptyText = "_なし_"): string[] {
  if (rows.length === 0) return [emptyText]
  return [
    "| 項目 | 型 | 必須 | 説明 | 制約 |",
    "| --- | --- | --- | --- | --- |",
    ...rows.map((row) => `| \`${escapeMarkdown(row.name)}\` | \`${escapeMarkdown(row.type)}\` | ${row.required ? "yes" : "no"} | ${escapeMarkdown(row.description)} | ${row.constraints} |`)
  ]
}

function renderRequestData(api: OpenApiDocument, operation: OperationObject): string[] {
  const body = operation.requestBody
  if (!body || typeof body !== "object" || !("content" in body)) return ["_なし_"]
  const content = contentRows(api, body.content)
  if (content.length === 0) return ["_なし_"]
  const lines: string[] = []
  for (const item of content) {
    lines.push(`Media type: \`${item.mediaType}\``)
    lines.push("")
    lines.push(...fieldTable(item.rows))
    lines.push("")
  }
  return lines
}

function renderResponses(api: OpenApiDocument, operation: OperationObject): string[] {
  const responses = responseRows(api, operation.responses)
  if (responses.length === 0) return ["_なし_"]
  const lines: string[] = []
  for (const response of responses) {
    lines.push(`##### \`${response.status}\` ${response.description}`)
    lines.push("")
    lines.push(`Media type: \`${response.mediaType}\``)
    lines.push("")
    lines.push(...fieldTable(response.rows, response.mediaType === "-" ? "_body なし_" : "_項目なし_"))
    lines.push("")
  }
  return lines
}

function renderOperationDetail(api: OpenApiDocument, method: string, path: string, operation: OperationObject): string {
  const lines: string[] = []
  lines.push(`# ${operationKey(method, path)}`)
  lines.push("")
  lines.push("<!-- This file is generated by npm run docs:openapi. Do not edit manually. -->")
  lines.push("")
  lines.push("[API 一覧へ戻る](../openapi.md)")
  lines.push("")
  lines.push(`Summary: ${operation.summary ?? "-"}`)
  lines.push("")
  lines.push(operation.description ?? "-")
  lines.push("")
  lines.push("## Headers")
  lines.push("")
  lines.push(...fieldTable(parameterRows(parametersByGroup(operation, "header"))))
  lines.push("")
  lines.push("## Path Parameters")
  lines.push("")
  lines.push(...fieldTable(parameterRows(parametersByGroup(operation, "path"))))
  lines.push("")
  lines.push("## Query Parameters")
  lines.push("")
  lines.push(...fieldTable(parameterRows(parametersByGroup(operation, "query"))))
  lines.push("")
  lines.push("## Data")
  lines.push("")
  lines.push(...renderRequestData(api, operation))
  lines.push("")
  lines.push("## Responses")
  lines.push("")
  lines.push(...renderResponses(api, operation))
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`
}

function renderMarkdown(api: OpenApiDocument): string {
  const title = api.info?.title ?? "OpenAPI Reference"
  const version = api.info?.version ?? "-"
  const description = api.info?.description ?? ""
  const lines = [
    `# ${title}`,
    "",
    "<!-- This file is generated by npm run docs:openapi. Do not edit manually. -->",
    "",
    `OpenAPI: \`${api.openapi ?? "-"}\``,
    `Version: \`${version}\``,
    "",
    description,
    "",
    "## Operations",
    "",
    ...operationRows(api)
  ]
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`
}

async function main(): Promise<void> {
  const { default: app } = await import("./app.js")
  const response = await app.request("/openapi.json")
  if (!response.ok) {
    throw new Error(`Failed to generate OpenAPI document: ${response.status}`)
  }

  const api = enrichOpenApiDocument((await response.json()) as OpenApiDocument)
  const errors = validateOpenApiDocument(api)
  if (errors.length > 0) {
    throw new Error(`OpenAPI document quality check failed:\n${errors.map((error) => `- ${error}`).join("\n")}`)
  }

  await mkdir(outputDir, { recursive: true })
  await rm(openApiOutputPath, { force: true })
  await rm(operationOutputDir, { force: true, recursive: true })
  await mkdir(operationOutputDir, { recursive: true })
  await writeFile(markdownOutputPath, renderMarkdown(api))
  for (const entry of operationEntries(api)) {
    await writeFile(join(operationOutputDir, entry.fileName), renderOperationDetail(api, entry.method, entry.path, entry.operation))
  }

  console.log(`Generated ${markdownOutputPath}`)
  console.log(`Generated ${operationOutputDir}`)
}

await main()
