import { renderMarkdownArtifacts } from "../generate-openapi-docs.js"
import {
  API_CODE_DOCUMENT_NAMES,
  type ApiCodeAnalysis,
  type ApiCodeAnalysisResult,
  type CallSite,
  type DataAccess,
  type MessageSpec,
  type RenderedApiCodeDocs,
  type SourceLocation
} from "./model.js"

const GENERATED_COMMENT = "<!-- This file is generated by npm run docs:api-code. Do not edit manually. -->"
const DETAIL_FUNCTION_DEPTH = 2
const API_BRANCH_DEPTH = 1

export function renderApiCodeDocs(result: ApiCodeAnalysisResult): RenderedApiCodeDocs {
  const files = new Map<string, string>()
  const openApiArtifacts = new Map(renderMarkdownArtifacts(result.api).map((artifact) => [artifact.relativePath, artifact.content]))
  for (const operation of result.operations) {
    const prefix = operation.slug
    files.set(`${prefix}/detail-design_gen.md`, renderDetailDesign(operation))
    files.set(`${prefix}/if_gen.md`, renderInterface(operation, openApiArtifacts))
    files.set(`${prefix}/messages_gen.md`, renderMessages(operation))
    files.set(`${prefix}/query_gen.md`, renderQueries(operation))
    files.set(`${prefix}/sequence_gen.md`, renderSequence(operation))
    files.set(`${prefix}/unit-test_gen.md`, renderUnitTests(operation))
  }
  files.set("index.md", renderIndex(result.operations))
  files.set("manifest.json", renderManifest(result))
  return {
    files,
    operationCount: result.operations.length,
    documentCount: result.operations.length * API_CODE_DOCUMENT_NAMES.length
  }
}

function renderDetailDesign(operation: ApiCodeAnalysis): string {
  const lines = header(`${operation.method.toUpperCase()} ${operation.path} 詳細設計`)
  const branches = projectedBranches(operation)
  const functions = operation.functions.filter((item) => item.depth <= DETAIL_FUNCTION_DEPTH)
  lines.push(
    "## 1. API の役割",
    "",
    operation.summary,
    "",
    operation.description || "説明は実装と runtime contract から取得できませんでした。",
    "",
    "| 項目 | 内容 |",
    "| --- | --- |",
    `| Method | \`${md(operation.method.toUpperCase())}\` |`,
    `| Path | \`${md(operation.path)}\` |`,
    `| OpenAPI contract | ${operation.hasOpenApiContract ? "あり（runtime `/openapi.json`）" : "なし（コード上の route のみ）"} |`,
    `| Route 定義 | ${location(operation.routeLocation)} |`,
    `| Handler | ${location(operation.handlerLocation)} |`,
    "",
    "## 2. 主処理",
    ""
  )
  if (operation.flow.length === 0) {
    lines.push("_handler body から逐次処理を抽出できませんでした。_", "")
  } else {
    lines.push("| # | 深さ | 種別 | 自然言語での処理 | コード根拠 | 実装位置 |", "| ---: | ---: | --- | --- | --- | --- |")
    for (const step of operation.flow) {
      lines.push(`| ${step.order} | ${step.depth} | ${flowKind(step.kind)} | ${md(step.description)} | \`${code(step.evidence)}\` | ${location(step.location)} |`)
    }
    lines.push("")
  }
  lines.push("## 3. 条件分岐・例外", "")
  if (branches.length === 0) {
    lines.push("_明示的な条件分岐、catch、loop、switch は到達実装から検出されませんでした。_", "")
  } else {
    lines.push("| # | 所属関数 | 種別 | 条件の意味 | 根拠式 | 実装位置 |", "| ---: | --- | --- | --- | --- | --- |")
    branches.forEach((branch, index) => {
      lines.push(`| B${pad(index + 1)} | \`${code(branch.functionName)}\` | ${branchKind(branch.kind)} | ${md(branch.description)} | \`${code(branch.condition)}\` | ${location(branch.location)} |`)
    })
    lines.push("")
  }
  lines.push("## 4. 到達する主要実装", "")
  lines.push(`handler を起点に TypeScript symbol を解決し、深さ ${DETAIL_FUNCTION_DEPTH} までの主要関数・method を列挙しています。深い helper を含む全到達関数は ${operation.functions.length} 件で、永続化・外部接続は深さにかかわらず次節へ集約しています。`, "")
  lines.push("| 深さ | Symbol | 責務 | 実装位置 |", "| ---: | --- | --- | --- |")
  for (const item of functions) {
    lines.push(`| ${item.depth} | \`${code(item.name)}\` | ${md(item.summary)} | ${location(item.location)} |`)
  }
  lines.push("", "## 5. データ・外部境界", "")
  appendDataAccessTable(lines, operation.dataAccess)
  lines.push("## 6. 応答・メッセージ", "")
  appendMessageSummary(lines, operation.messages)
  lines.push("## 7. テスト対応", "")
  appendTestSummary(lines, operation)
  lines.push("## 8. 解析上の注意", "")
  appendWarnings(lines, operation.warnings)
  lines.push(
    "- 記載内容は route、runtime OpenAPI、handler から到達する repository 内 symbol、既存 test を解析した派生成果物です。",
    `- 可読性のため、詳細設計と unit test の分岐は handler と直下関数（深さ ${API_BRANCH_DEPTH} まで）へ絞り、深い共通 helper の内部分岐は API 固有要件として重複掲載しません。`,
    "- 文書生成専用 annotation、decorator、コメント、API 別設定表は入力にしていません。",
    "- interface / dynamic dispatch の実装先を TypeScript checker が一意に解決できない場合、logical store call までを確定情報として記載します。",
    ""
  )
  return finish(lines)
}

function renderInterface(operation: ApiCodeAnalysis, artifacts: Map<string, string>): string {
  const lines = header(`${operation.method.toUpperCase()} ${operation.path} IF仕様`)
  lines.push(
    `- 実装 route: ${location(operation.routeLocation)}`,
    `- contract source: ${operation.hasOpenApiContract ? "runtime `GET /openapi.json`" : "route 実装のみ（OpenAPI 未登録）"}`,
    ""
  )
  const artifact = artifacts.get(`openapi/${operation.slug}.md`)
  if (artifact) {
    const artifactLines = artifact.trimEnd().split("\n")
    const summaryIndex = artifactLines.findIndex((line) => line.startsWith("Summary:"))
    lines.push(...artifactLines.slice(summaryIndex >= 0 ? summaryIndex : 0), "")
    return finish(lines)
  }

  const pathParameters = [...operation.path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]).filter((value): value is string => Boolean(value))
  const implementationResponses = operation.calls.filter((call) => call.depth === 0 && call.category === "response")
  lines.push(
    `Summary: ${operation.summary}`,
    "",
    operation.description,
    "",
    "## Headers",
    "",
    "OpenAPI schema がないため、handler 内の header access は詳細設計・sequence を参照してください。",
    "",
    "## Path Parameters",
    ""
  )
  if (pathParameters.length === 0) lines.push("_なし_", "")
  else {
    lines.push("| 項目 | 根拠 |", "| --- | --- |")
    for (const parameter of pathParameters) lines.push(`| \`${md(parameter)}\` | route path \`${md(operation.path)}\` |`)
    lines.push("")
  }
  lines.push(
    "## Query Parameters",
    "",
    "OpenAPI schema 未登録のため、型・必須条件は機械的に確定できません。",
    "",
    "## Data",
    "",
    "OpenAPI schema 未登録のため、request body schema は確定できません。",
    "",
    "## Responses",
    ""
  )
  if (implementationResponses.length === 0) lines.push("handler の明示 response call は検出されませんでした。", "")
  else {
    lines.push("| Status | Body/処理 | 根拠 |", "| --- | --- | --- |")
    for (const response of implementationResponses) {
      lines.push(`| \`${md(response.arguments[1] ?? "default")}\` | \`${code(response.arguments[0] ?? response.expression)}\` | ${location(response.location)} |`)
    }
    lines.push("")
  }
  return finish(lines)
}

function renderMessages(operation: ApiCodeAnalysis): string {
  const lines = header(`${operation.method.toUpperCase()} ${operation.path} メッセージ仕様`)
  lines.push(
    "## 生成根拠",
    "",
    "- OpenAPI response description",
    "- handler と到達関数の `c.json({ error/message })`",
    "- `HTTPException` / `Error` の literal message",
    "- logger call と SSE event の literal message",
    "",
    "## メッセージ一覧",
    ""
  )
  if (operation.messages.length === 0) {
    lines.push("_実装から静的に確定できる message literal はありません。_", "")
  } else {
    lines.push("| ID | 種別 | Status/Event | メッセージ | 発生条件 | 実装根拠 |", "| --- | --- | --- | --- | --- | --- |")
    operation.messages.forEach((message, index) => {
      lines.push(`| M${pad(index + 1)} | ${messageKind(message.kind)} | \`${md(message.status ?? "-")}\` | ${md(message.text)} | ${md(message.trigger)} | ${message.location ? location(message.location) : "runtime OpenAPI"} |`)
    })
    lines.push("")
  }
  lines.push(
    "## 読み方",
    "",
    "- `contract` は API contract 上の応答説明であり、実装 literal と同一とは限りません。",
    "- `http-response` / `exception` / `event` / `log` は実コードに存在する literal を根拠にしています。",
    "- 動的に組み立てる文字列は式として確定できる場合だけ掲載し、推測した文面は補いません。",
    ""
  )
  return finish(lines)
}

function renderQueries(operation: ApiCodeAnalysis): string {
  const lines = header(`${operation.method.toUpperCase()} ${operation.path} Query・永続化仕様`)
  const storeAccess = operation.dataAccess.filter((item) => item.boundary === "store")
  const externalAccess = operation.dataAccess.filter((item) => item.boundary === "external")
  lines.push(
    "このアプリケーションは API operation ごとの SQL ファイルを持たないため、handler から到達する store / object / vector / external port の実呼び出しを query 単位として記載します。",
    "",
    "## Store・永続化操作",
    ""
  )
  appendBoundaryTable(lines, storeAccess)
  lines.push("## 外部サービス操作", "")
  appendBoundaryTable(lines, externalAccess)
  lines.push(
    "## 解析境界",
    "",
    "- store interface call は API 実装が要求する論理操作です。local / DynamoDB / S3 など実 adapter の選択は `createDependencies()` の runtime 設定に従います。",
    "- interface 経由で複数 adapter があり TypeScript symbol が一意にならない場合、実装を推測せず interface call を記載します。",
    "- 文書生成専用 query metadata や API 別 CRUD 定義は参照していません。",
    ""
  )
  return finish(lines)
}

function renderSequence(operation: ApiCodeAnalysis): string {
  const lines = header(`${operation.method.toUpperCase()} ${operation.path} シーケンス`)
  const sequenceCalls = projectedSequenceCalls(operation)
  const branches = projectedBranches(operation)
  lines.push("## シーケンス図", "", "```mermaid", "sequenceDiagram", "  autonumber")
  lines.push("  participant Client as Client", "  participant API as Hono API", "  participant Auth as Auth/Validation", "  participant Service as Service", "  participant Store as Store", "  participant External as External")
  lines.push(`  Client->>API: ${mermaid(`${operation.method.toUpperCase()} ${operation.path}`)}`)
  for (const branch of branches.filter((item) => item.functionName === operation.handlerName)) {
    lines.push(`  Note over API: ${mermaid(`分岐 ${branch.description}`)}`)
  }
  for (const call of sequenceCalls) lines.push(renderSequenceCall(call))
  if (!sequenceCalls.some((call) => call.category === "response")) lines.push("  API-->>Client: handler の処理結果")
  lines.push("```", "", "## 処理順とコード対応", "")
  if (sequenceCalls.length === 0) lines.push("_認可・検証・service・store・response に分類できる call は検出されませんでした。_", "")
  else {
    lines.push("| # | Caller | 境界 | 処理 | コード | 実装位置 |", "| ---: | --- | --- | --- | --- | --- |")
    sequenceCalls.forEach((call, index) => {
      lines.push(`| ${index + 1} | \`${code(call.caller)}\` | ${callCategory(call.category)} | ${md(call.description)} | \`${code(call.expression)}\` | ${location(call.location)} |`)
    })
    lines.push("")
  }
  lines.push("## 分岐", "")
  if (branches.length === 0) lines.push("_handler と直下関数に明示分岐なし_", "")
  else {
    lines.push("| ID | Function | 条件 | 実装位置 |", "| --- | --- | --- | --- |")
    branches.forEach((branch, index) => lines.push(`| B${pad(index + 1)} | \`${code(branch.functionName)}\` | ${md(branch.description)} | ${location(branch.location)} |`))
    lines.push("")
  }
  return finish(lines)
}

function renderSequenceCall(call: CallSite): string {
  const label = mermaid(call.description)
  if (call.category === "authorization" || call.category === "validation") return `  API->>Auth: ${label}`
  if (call.category === "service") return `  API->>Service: ${label}`
  if (call.category === "data") return `  Service->>Store: ${label}`
  if (call.category === "external") return `  Service->>External: ${label}`
  if (call.category === "response") return `  API-->>Client: ${label}`
  return `  API->>API: ${label}`
}

function renderUnitTests(operation: ApiCodeAnalysis): string {
  const lines = header(`${operation.method.toUpperCase()} ${operation.path} Unit Test仕様`)
  const branches = projectedBranches(operation)
  lines.push(
    "## 1. 既存テストとの対応",
    "",
    "次の関連付けは test body 内の request path または到達 symbol 参照を静的に照合した結果です。assertion の完全充足を意味しません。",
    ""
  )
  appendTestSummary(lines, operation)
  lines.push("## 2. 実装分岐から導くテスト要因", "")
  if (branches.length === 0) lines.push("_handler と直下関数に明示的な分岐はありません。_", "")
  else {
    lines.push("| Factor | Function | 種別 | 条件・発生要因 | 実装位置 |", "| --- | --- | --- | --- | --- |")
    branches.forEach((branch, index) => {
      lines.push(`| F${pad(index + 1)} | \`${code(branch.functionName)}\` | ${branchKind(branch.kind)} | ${md(branch.description)} | ${location(branch.location)} |`)
    })
    lines.push("")
  }
  lines.push("## 3. コード由来テストケース", "")
  lines.push("| Case | シナリオ | 期待観点 | 根拠 |", "| --- | --- | --- | --- |")
  lines.push(`| TC001 | 正常系 | ${md(operation.summary)} が成功 response を返す。 | ${location(operation.handlerLocation)} |`)
  let caseNumber = 2
  branches.forEach((branch, index) => {
    if (branch.kind === "catch") {
      lines.push(`| TC${pad(caseNumber++)} | F${pad(index + 1)}: 例外発生 | catch が例外を握りつぶさず、実装どおり応答変換または再送出する。 | ${location(branch.location)} |`)
    } else if (branch.kind === "loop") {
      lines.push(`| TC${pad(caseNumber++)} | F${pad(index + 1)}: 0件 | 反復対象が空でも不正な副作用や例外を生じない。 | ${location(branch.location)} |`)
      lines.push(`| TC${pad(caseNumber++)} | F${pad(index + 1)}: 複数件 | 各要素を順に処理し、順序・終了条件を守る。 | ${location(branch.location)} |`)
    } else {
      lines.push(`| TC${pad(caseNumber++)} | F${pad(index + 1)}: 条件成立 | ${md(branch.description)} 場合の response / side effect が実装どおりである。 | ${location(branch.location)} |`)
      lines.push(`| TC${pad(caseNumber++)} | F${pad(index + 1)}: 条件不成立 | 反対側または後続処理へ進み、成立側の副作用を行わない。 | ${location(branch.location)} |`)
    }
  })
  const statuses = [...new Set(operation.messages
    .map((message) => message.status)
    .filter((status): status is string => typeof status === "string" && status !== "default" && /^\d+$/.test(status)))]
  for (const status of statuses) {
    lines.push(`| TC${pad(caseNumber++)} | HTTP ${md(status)} | contract または実装 message と status の組み合わせを確認する。 | \`messages_gen.md\` |`)
  }
  lines.push(
    "",
    "## 4. 検証方針",
    "",
    "- route test は method/path、認証・認可、入力検証、status、response body を確認する。",
    "- service/store test は query_gen に列挙した read/create/update/delete と失敗時の副作用を確認する。",
    `- API 単位の要因は handler と直下関数（深さ ${API_BRANCH_DEPTH} まで）の分岐から生成し、深い共通 helper の単体要因は重複展開しない。`,
    "- 上表は実装分岐から導いた候補であり、既存 test と照合していない行を『テスト済み』とは扱わない。",
    ""
  )
  return finish(lines)
}

function renderIndex(operations: ApiCodeAnalysis[]): string {
  const lines = header("API コード対応ドキュメント一覧")
  lines.push(
    "runtime OpenAPI と TypeScript 実装を対応付け、各 API の詳細設計、IF、メッセージ、query、sequence、unit test 仕様を生成しています。",
    "",
    `- API 数: ${operations.length}`,
    `- API 別文書数: ${API_CODE_DOCUMENT_NAMES.length}`,
    `- 文書総数: ${operations.length * API_CODE_DOCUMENT_NAMES.length}`,
    "",
    "| Method | Path | Summary | OpenAPI | 6文書 |",
    "| --- | --- | --- | --- | --- |"
  )
  for (const operation of operations) {
    const links = API_CODE_DOCUMENT_NAMES.map((name) => `[${name.replace("_gen.md", "")}](${operation.slug}/${name})`).join(" / ")
    lines.push(`| \`${md(operation.method.toUpperCase())}\` | \`${md(operation.path)}\` | ${md(operation.summary)} | ${operation.hasOpenApiContract ? "yes" : "no"} | ${links} |`)
  }
  lines.push(
    "",
    "## Source of truth",
    "",
    "- IF: runtime `GET /openapi.json` と route 実装",
    "- 処理・分岐・sequence: route handler と TypeScript symbol call graph",
    "- query: handler から到達する store / object / vector / external port call",
    "- message: OpenAPI response description と実装 literal",
    "- unit test: 実装分岐と既存 `.test.ts` の参照",
    "",
    "文書生成専用の metadata を production 実装へ追加せず、コード変更後は `npm run docs:api-code` で再生成し、`npm run docs:api-code:check` で stale 差分を検出します。",
    ""
  )
  return finish(lines)
}

function renderManifest(result: ApiCodeAnalysisResult): string {
  const manifest = {
    schemaVersion: 1,
    generator: "npm run docs:api-code",
    sourceRoot: result.sourceRoot,
    operationCount: result.operations.length,
    documentsPerOperation: [...API_CODE_DOCUMENT_NAMES],
    operations: result.operations.map((operation) => ({
      method: operation.method.toUpperCase(),
      path: operation.path,
      slug: operation.slug,
      openApi: operation.hasOpenApiContract,
      routeSource: formatLocation(operation.routeLocation),
      handlerSource: formatLocation(operation.handlerLocation),
      functionCount: operation.functions.length,
      branchCount: operation.branches.length,
      projectedBranchCount: projectedBranches(operation).length,
      dataAccessCount: operation.dataAccess.length,
      relatedTestCount: operation.tests.length
    }))
  }
  return `${JSON.stringify(manifest, null, 2)}\n`
}

function projectedBranches(operation: ApiCodeAnalysis) {
  return operation.branches.filter((branch) => branch.depth <= API_BRANCH_DEPTH)
}

function projectedSequenceCalls(operation: ApiCodeAnalysis): CallSite[] {
  return operation.calls.filter((call) => {
    if (call.category === "utility") return false
    if (call.depth === 0) return true
    if (call.category === "data" || call.category === "external") return true
    return call.depth <= API_BRANCH_DEPTH && (call.category === "service" || call.category === "response")
  })
}

function header(title: string): string[] {
  return [GENERATED_COMMENT, "", `# ${title}`, ""]
}

function finish(lines: string[]): string {
  return `${lines.join("\n").replace(/[ \t]+$/gm, "").replace(/\n{3,}/g, "\n\n").trim()}\n`
}

function md(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br>")
}

function code(value: string): string {
  return md(value).replaceAll("`", "\\`")
}

function location(value: SourceLocation): string {
  return `\`${code(formatLocation(value))}\``
}

function formatLocation(value: SourceLocation): string {
  return `${value.path}:${value.line}${value.symbol ? ` (${value.symbol})` : ""}`
}

function pad(value: number): string {
  return String(value).padStart(3, "0")
}

function flowKind(value: string): string {
  const values: Record<string, string> = {
    authorization: "認証・認可",
    validation: "入力検証",
    branch: "分岐",
    call: "呼び出し",
    response: "応答",
    exception: "例外",
    loop: "反復",
    state: "状態"
  }
  return values[value] ?? value
}

function branchKind(value: string): string {
  const values: Record<string, string> = { if: "if", conditional: "三項条件", catch: "catch", loop: "loop", switch: "switch" }
  return values[value] ?? value
}

function messageKind(value: string): string {
  const values: Record<string, string> = {
    "http-response": "HTTP 実装応答",
    exception: "例外",
    log: "ログ",
    event: "SSE/Event",
    contract: "OpenAPI contract"
  }
  return values[value] ?? value
}

function callCategory(value: string): string {
  const values: Record<string, string> = {
    authorization: "Auth",
    validation: "Validation",
    response: "HTTP/SSE",
    service: "Service",
    data: "Store",
    external: "External",
    utility: "Utility"
  }
  return values[value] ?? value
}

function dataKind(value: string): string {
  const values: Record<string, string> = { read: "参照", create: "作成・追記", update: "更新", delete: "削除", execute: "実行" }
  return values[value] ?? value
}

function appendDataAccessTable(lines: string[], rows: DataAccess[]): void {
  if (rows.length === 0) {
    lines.push("_到達実装に store / external boundary call はありません。_", "")
    return
  }
  lines.push("| 種別 | 境界 | Target | Operation | 目的 | Caller | 実装位置 |", "| --- | --- | --- | --- | --- | --- | --- |")
  for (const row of rows) {
    lines.push(`| ${dataKind(row.kind)} | ${row.boundary === "store" ? "Store" : "External"} | \`${code(row.target)}\` | \`${code(row.operation)}\` | ${md(row.purpose)} | \`${code(row.caller)}\` | ${location(row.location)} |`)
  }
  lines.push("")
}

function appendBoundaryTable(lines: string[], rows: DataAccess[]): void {
  if (rows.length === 0) {
    lines.push("_該当操作なし_", "")
    return
  }
  lines.push("| # | CRUD/実行 | Target | Method | 自然言語での目的 | Caller | コード根拠 |", "| ---: | --- | --- | --- | --- | --- | --- |")
  rows.forEach((row, index) => {
    lines.push(`| ${index + 1} | ${dataKind(row.kind)} | \`${code(row.target)}\` | \`${code(row.operation)}\` | ${md(row.purpose)} | \`${code(row.caller)}\` | ${location(row.location)} |`)
  })
  lines.push("")
}

function appendMessageSummary(lines: string[], messages: MessageSpec[]): void {
  if (messages.length === 0) {
    lines.push("_静的に確定できる response / exception / event / log message はありません。_", "")
    return
  }
  lines.push("| 種別 | Status/Event | 内容 | 発生条件 |", "| --- | --- | --- | --- |")
  for (const message of messages) lines.push(`| ${messageKind(message.kind)} | \`${md(message.status ?? "-")}\` | ${md(message.text)} | ${md(message.trigger)} |`)
  lines.push("")
}

function appendTestSummary(lines: string[], operation: ApiCodeAnalysis): void {
  if (operation.tests.length === 0) {
    lines.push("_静的に直接対応を確認できた test case はありません。`unit-test_gen.md` のコード由来ケースは未実装テスト候補として扱います。_", "")
    return
  }
  lines.push("| 関連 | Test case | 実装位置 |", "| --- | --- | --- |")
  for (const test of operation.tests) {
    lines.push(`| ${test.relation === "route" ? "route request" : "到達 symbol"} | ${md(test.name)} | ${location(test.location)} |`)
  }
  lines.push("")
}

function appendWarnings(lines: string[], warnings: string[]): void {
  if (warnings.length === 0) {
    lines.push("- 既知の operation 固有 warning はありません。", "")
    return
  }
  for (const warning of warnings) lines.push(`- ${warning}`)
  lines.push("")
}

function mermaid(value: string): string {
  const text = value
    .replaceAll("\n", " ")
    .replaceAll(":", "：")
    .replaceAll(";", "、")
    .replaceAll("<", "＜")
    .replaceAll(">", "＞")
    .replaceAll("#", "No.")
    .replaceAll("`", "")
  return text.length <= 180 ? text : `${text.slice(0, 179)}…`
}
