import tempfile
import unittest
from pathlib import Path

from scripts import validate_docs


def _valid_repository(repo: Path) -> Path:
    docs = repo / "docs"
    for name in validate_docs.ALLOWED_DOC_ROOTS:
        (docs / name).mkdir(parents=True)
    (docs / "4_運用_OPS" / "21_監視_MONITORING").mkdir()
    (docs / "1_要求_REQ" / "README.md").write_text("# 要求\n", encoding="utf-8")
    product = docs / "1_要求_REQ" / "11_製品要求_PRODUCT"
    product.mkdir()
    ids = [
        *(f"FR-{number:03d}" for number in range(56, 94)),
        *(f"SQ-{number:03d}" for number in range(5, 16)),
    ]
    task_name = "20260713-0000-example.md"
    (product / "REQUIREMENTS_BASELINE_202607.md").write_text(
        "\n".join(ids) + f"\n`{task_name}`\n", encoding="utf-8"
    )
    requirement_dir = product / "01_機能要求_FUNCTIONAL"
    requirement_dir.mkdir()
    (requirement_dir / "REQ_FUNCTIONAL_056.md").write_text(
        "- FR-056: 検証可能な要求\n\n## 受け入れ条件\n\n- 確認できること。\n",
        encoding="utf-8",
    )
    (repo / "tasks" / "todo").mkdir(parents=True)
    (repo / "tasks" / "todo" / task_name).write_text("# todo\n", encoding="utf-8")
    (docs / "generated" / "openapi.md").write_text(
        "<!-- This file is generated by npm run docs:openapi. Do not edit manually. -->\n",
        encoding="utf-8",
    )
    return repo


class ValidateDocsTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp_dir.cleanup)
        self.repo = _valid_repository(Path(self.temp_dir.name))

    def test_valid_repository(self) -> None:
        self.assertEqual(validate_docs.validate_repository(self.repo), [])

    def test_rejects_unexpected_docs_root(self) -> None:
        (self.repo / "docs" / "notes").mkdir()
        self.assertTrue(
            any(
                "許可されない項目" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )

    def test_rejects_handwritten_generated_file(self) -> None:
        (self.repo / "docs" / "generated" / "manual.md").write_text(
            "manual\n", encoding="utf-8"
        )
        self.assertTrue(
            any(
                "生成元不明" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )

    def test_accepts_registered_api_code_tree(self) -> None:
        api_code = self.repo / "docs" / "generated" / "api-code"
        operation = api_code / "get-health"
        operation.mkdir(parents=True)
        marker = (
            "<!-- This file is generated by npm run docs:api-code. "
            "Do not edit manually. -->\n"
        )
        (api_code / "index.md").write_text(marker, encoding="utf-8")
        (api_code / "manifest.json").write_text(
            '{"generator":"npm run docs:api-code"}\n', encoding="utf-8"
        )
        for name in validate_docs.API_CODE_DOCUMENT_NAMES:
            (operation / name).write_text(marker, encoding="utf-8")

        self.assertEqual(validate_docs.validate_repository(self.repo), [])

    def test_rejects_unknown_api_code_document(self) -> None:
        operation = (
            self.repo / "docs" / "generated" / "api-code" / "get-health"
        )
        operation.mkdir(parents=True)
        (operation / "manual.md").write_text(
            "generated by npm run docs:api-code\n", encoding="utf-8"
        )

        self.assertTrue(
            any(
                "生成元不明" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )

    def test_rejects_nested_api_code_directory(self) -> None:
        nested = (
            self.repo
            / "docs"
            / "generated"
            / "api-code"
            / "get-health"
            / "nested"
        )
        nested.mkdir(parents=True)

        self.assertTrue(
            any(
                "未登録のディレクトリ" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )

    def test_rejects_missing_baseline_todo(self) -> None:
        (self.repo / "tasks" / "todo" / "20260713-0000-example.md").unlink()
        self.assertTrue(
            any(
                "todo が存在しません" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )

    def test_rejects_legacy_live_reference(self) -> None:
        (self.repo / "README.md").write_text(
            "see docs/" + "spec-recovery\n", encoding="utf-8"
        )
        self.assertTrue(
            any(
                "旧 docs path" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )

    def test_rejects_broken_markdown_link(self) -> None:
        (self.repo / "README.md").write_text(
            "[missing](docs/missing.md)\n", encoding="utf-8"
        )
        self.assertTrue(
            any(
                "Markdown link が存在しません" in error
                for error in validate_docs.validate_repository(self.repo)
            )
        )


if __name__ == "__main__":
    unittest.main()
