#!/usr/bin/env python3
"""Validate the canonical docs layout and its traceability invariants."""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import unquote


ALLOWED_DOC_ROOTS = {
    "1_要求_REQ",
    "2_アーキテクチャ_ARC",
    "3_設計_DES",
    "4_運用_OPS",
    "generated",
}
ALLOWED_OPS_ROOTS = {"21_監視_MONITORING"}
GENERATORS = {
    "openapi": ("openapi", "generated by npm run docs:openapi"),
    "web": ("web-features", "tools/web-inventory/generate-web-inventory.mjs"),
    "infra": ("infra-inventory", "tools/infra-inventory/generate-infra-inventory.mjs"),
}
REQUIREMENT_FILE = re.compile(
    r"^REQ_(FUNCTIONAL|NON_FUNCTIONAL|SERVICE_QUALITY|TECHNICAL_CONSTRAINT)_\d+\.md$"
)
REQUIREMENT_BULLET = re.compile(r"^- (FR|NFR|SQ|TC)-\d+: \S", re.MULTILINE)
TODO_FILE = re.compile(r"`?(20\d{6}-[a-z0-9-]+\.md)`?")
MARKDOWN_LINK = re.compile(r"\[[^\]]+\]\((?P<target><[^>]+>|[^)\s]+)")


def validate_repository(repo_root: Path) -> list[str]:
    errors: list[str] = []
    docs_root = repo_root / "docs"
    if not docs_root.is_dir():
        return ["docs/ が存在しません"]

    _validate_doc_roots(docs_root, errors)
    _validate_ops(docs_root, errors)
    _validate_generated(docs_root, errors)
    _validate_requirements(docs_root, errors)
    _validate_baseline_todos(repo_root, docs_root, errors)
    _validate_live_references(repo_root, docs_root, errors)
    return errors


def _validate_doc_roots(docs_root: Path, errors: list[str]) -> None:
    actual = {entry.name for entry in docs_root.iterdir()}
    missing = sorted(ALLOWED_DOC_ROOTS - actual)
    unexpected = sorted(actual - ALLOWED_DOC_ROOTS)
    if missing:
        errors.append(f"docs/ の必須ディレクトリが不足: {', '.join(missing)}")
    if unexpected:
        errors.append(f"docs/ 直下に許可されない項目: {', '.join(unexpected)}")
    for name in sorted(ALLOWED_DOC_ROOTS & actual):
        if not (docs_root / name).is_dir():
            errors.append(f"docs/{name} はディレクトリでなければなりません")


def _validate_ops(docs_root: Path, errors: list[str]) -> None:
    ops_root = docs_root / "4_運用_OPS"
    if not ops_root.is_dir():
        return
    actual = {entry.name for entry in ops_root.iterdir()}
    unexpected = sorted(actual - ALLOWED_OPS_ROOTS)
    missing = sorted(ALLOWED_OPS_ROOTS - actual)
    if unexpected:
        errors.append(f"4_運用_OPS/ に許可されない項目: {', '.join(unexpected)}")
    if missing:
        errors.append(f"4_運用_OPS/ の必須ディレクトリが不足: {', '.join(missing)}")


def _validate_generated(docs_root: Path, errors: list[str]) -> None:
    generated_root = docs_root / "generated"
    if not generated_root.is_dir():
        return
    for path in sorted(generated_root.rglob("*")):
        if path.is_symlink():
            errors.append(f"generated/ に symlink は置けません: {path.relative_to(docs_root)}")
            continue
        if path.is_dir():
            relative = path.relative_to(generated_root)
            if len(relative.parts) != 1 or relative.name not in {
                item[0] for item in GENERATORS.values()
            }:
                errors.append(f"generated/ に未登録のディレクトリ: {relative}")
            continue

        relative = path.relative_to(generated_root)
        generator = _generator_for(relative)
        if generator is None:
            errors.append(f"generated/ に生成元不明のファイル: {relative}")
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            errors.append(f"generated/ の出力は UTF-8 text に限定します: {relative}")
            continue
        if generator not in text:
            errors.append(f"generated/ の provenance marker がありません: {relative}")


def _generator_for(relative: Path) -> str | None:
    if len(relative.parts) == 2:
        for directory, marker in GENERATORS.values():
            if relative.parts[0] == directory and relative.suffix == ".md":
                return marker
        return None
    if len(relative.parts) != 1:
        return None
    name = relative.name
    if name == "openapi.md":
        return GENERATORS["openapi"][1]
    if name.startswith("web-") and relative.suffix in {".md", ".json"}:
        return GENERATORS["web"][1]
    if name in {"infra-inventory.md", "infra-resource-inventory.json"}:
        return GENERATORS["infra"][1]
    return None


def _validate_requirements(docs_root: Path, errors: list[str]) -> None:
    product_root = docs_root / "1_要求_REQ" / "11_製品要求_PRODUCT"
    if not product_root.is_dir():
        errors.append("製品要求ディレクトリが存在しません")
        return
    for path in sorted(product_root.rglob("REQ_*.md")):
        if not REQUIREMENT_FILE.match(path.name):
            continue
        text = path.read_text(encoding="utf-8")
        relative = path.relative_to(docs_root)
        if not REQUIREMENT_BULLET.search(text):
            errors.append(f"要求 bullet がありません: {relative}")
        if "受け入れ条件" not in text:
            errors.append(f"受け入れ条件がありません: {relative}")


def _validate_baseline_todos(repo_root: Path, docs_root: Path, errors: list[str]) -> None:
    baseline = (
        docs_root
        / "1_要求_REQ"
        / "11_製品要求_PRODUCT"
        / "REQUIREMENTS_BASELINE_202607.md"
    )
    if not baseline.is_file():
        errors.append("REQUIREMENTS_BASELINE_202607.md が存在しません")
        return
    text = baseline.read_text(encoding="utf-8")
    for name in sorted(set(TODO_FILE.findall(text))):
        if not (repo_root / "tasks" / "todo" / name).is_file():
            errors.append(f"baseline が参照する todo が存在しません: tasks/todo/{name}")
    for number in range(56, 94):
        requirement_id = f"FR-{number:03d}"
        if requirement_id not in text:
            errors.append(f"baseline に要求 ID がありません: {requirement_id}")
    for number in range(5, 16):
        requirement_id = f"SQ-{number:03d}"
        if requirement_id not in text:
            errors.append(f"baseline に要求 ID がありません: {requirement_id}")


def _validate_live_references(repo_root: Path, docs_root: Path, errors: list[str]) -> None:
    legacy_paths = [
        "docs/" + "spec-recovery",
        "docs/" + "spec/",
        "docs/" + "REQUIREMENTS.md",
        "docs/" + "ARCHITECTURE.md",
        "docs/" + "OPERATIONS.md",
        "docs/" + "LOCAL_VERIFICATION.md",
        "docs/" + "GITHUB_ACTIONS_DEPLOY.md",
        "docs/" + "API_EXAMPLES.md",
        "docs/" + "DOCS_STRUCTURE.md",
    ]
    candidates = [repo_root / "README.md", repo_root / "AGENTS.md"]
    candidates.extend(docs_root.rglob("*.md"))
    skills_root = repo_root / "skills"
    if skills_root.is_dir():
        candidates.extend(skills_root.rglob("*.md"))
    for task_state in ("do", "todo"):
        task_root = repo_root / "tasks" / task_state
        if task_root.is_dir():
            candidates.extend(task_root.rglob("*.md"))
    for path in sorted({item for item in candidates if item.is_file()}):
        text = path.read_text(encoding="utf-8")
        for legacy_path in legacy_paths:
            if legacy_path in text:
                errors.append(
                    f"旧 docs path が残っています: {path.relative_to(repo_root)}: {legacy_path}"
                )
        _validate_markdown_links(repo_root, path, text, errors)


def _validate_markdown_links(
    repo_root: Path, source: Path, text: str, errors: list[str]
) -> None:
    for match in MARKDOWN_LINK.finditer(text):
        raw_target = match.group("target").strip("<>")
        if raw_target.startswith(("#", "http://", "https://", "mailto:", "app://", "//")):
            continue
        target_without_anchor = unquote(raw_target.split("#", 1)[0])
        if not target_without_anchor:
            continue
        target = (
            repo_root / target_without_anchor.lstrip("/")
            if target_without_anchor.startswith("/")
            else source.parent / target_without_anchor
        )
        if not target.exists():
            errors.append(
                "Markdown link が存在しません: "
                f"{source.relative_to(repo_root)} -> {raw_target}"
            )


def main() -> int:
    repo_root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]
    errors = validate_repository(repo_root)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print("docs validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
